site_name: Adventure Ardeche
repo_url: https://github.com/Matt-Adventure-Ardeche/staffhandbook
edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github



plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors:
     enabled: true
     show_email_address: false